

services:
  mission-status:
    build: ./Mission_Service_Status
    ports:
      - "5000:5000"
    volumes:
      - ./Mission_Service_Status:/app
      - ./data:/app/data
  


  alert-system:
    build: ./alert_system
    volumes:
      - /var/log:/var/log:ro
 

volumes:
  data: